- name: install nginx
  apt:
    name: nginx
    state: present

- name: delete default nginx sites avariable
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/nginx/sites-available/default
    - /etc/nginx/sites-enabled/default

- name: copy nginx config
  template:
    src: templates/default.j2
    dest: /etc/nginx/sites-available/default

- name: create symlink nginx config
  file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    state: link
  notify:
    - reload nginx